### ISSUE TITLE
可以分享一下测试视频吗

### ISSUE THREAD

**Issue by 15850864092** [duchengyao/gpu-based-image-stitching#1]

**Comment by duchengyao** [comment]
一直都是用真实数据测试的，所以没有可以公开的测试视频。如果你有质量好的测试视频，可以帮你调好参数，然后集成到这个项目里。

**Comment by 15850864092** [comment]
缺少摄像头，想学习一下全景拼接，代码里面看的这四个视频没找到
std::string video_dir = "../datasets/air-4cam-mp4/";
std::vector<std::string> video_file_name = {"00.MP4", "01.MP4", "02.MP4", "03.MP4"};

**Comment by duchengyao** [comment]
刚才说过了视频不提供。

新手建议先调研一下全景拼接数据集，按照下面几个的顺序入门：

1. `opencv/samples/cpp/stitching.cpp` [[代码]](https://docs.opencv.org/4.7.0/db/db4/samples_2cpp_2stitching_8cpp-example.html)，代码讲解[[链接]](https://docs.opencv.org/4.7.0/d8/d19/tutorial_stitcher.html)
2. `opencv/samples/cpp/stitching_detailed.cpp` [[代码]](https://docs.opencv.org/4.7.0/d9/dd8/samples_2cpp_2stitching_detailed_8cpp-example.html)，本项目有关拼接参数生成的代码也来自这里 https://github.com/duchengyao/gpu-based-image-stitching/blob/5b316af4f8604bbf29c66c756afd4e7f2f3f1a1a/src/stitching_param_generater.cc#L3

另外，使用 Python 入门更快一些，可以参考 [Image Stitching with OpenCV and Python
](https://pyimagesearch.com/2018/12/17/image-stitching-with-opencv-and-python/)

**Comment by 15850864092** [comment]
谢谢指导！ @duchengyao

**Comment by duchengyao** [comment]
@15850864092 加油 ^_^

**Comment by duchengyao** [comment]
@15850864092 加油 ^_^

这个issue我先关掉了，如果有其它图像拼接方面的问题可以新建或重开 issue。

**Comment by duchengyao** [comment]
更新了测试数据集。
