### ISSUE TITLE
 master分支编译完运行./image-stitching报错

### ISSUE THREAD

**Issue by JaySlamer** [duchengyao/gpu-based-image-stitching#11]
Initializing video capture...
Done. 4 captures initialized.
[SensorDataInterface] Getting new images... Done.
[StitchingParamGenerator] Initializing...
Features in image #1: 5907
Features in image #2: 7816
Features in image #3: 8922
Features in image #4: 9958
Pairwise matching
Initial camera intrinsics #1:
K:
[1965.607133539436, 0, 1020.100223094943;
 0, 1857.907011218729, 505.1108079590136;
 0, 0, 1]
R:
[0.58653194, 0.09898302, -0.80385488;
 -0.0056669, 0.99298114, 0.11813634;
 0.8099063, -0.06473536, 0.58297616]
Initial camera intrinsics #2:
K:
[1956.01661889738, 0, 977.340049000778;
 0, 1858.884042017119, 452.6910870518543;
 0, 0, 1]
R:
[0.92483199, 0.025732817, -0.37950438;
 0.0063777552, 0.9965198, 0.08311265;
 0.38032237, -0.079285622, 0.9214493]
Initial camera intrinsics #3:
K:
[2027.827899767372, 0, 930.3503442356033;
 0, 1893.313732155926, 500.6865883801996;
 0, 0, 1]
R:
[0.93531376, -0.036812913, 0.35189939;
 -0.0016524697, 0.99410725, 0.1083877;
 -0.35381576, -0.10195801, 0.92974138]
Initial camera intrinsics #4:
K:
[2074.629130188972, 0, 981.7349428496174;
 0, 1914.593396587306, 501.3284095963675;
 0, 0, 1]
R:
[0.5458526, -0.10353445, 0.83145988;
 -0.0018850662, 0.99218208, 0.12478531;
 -0.83787918, -0.069681741, 0.54139]
Camera #1:
K:
[1965.607133539436, 0, 1020.100223094943;
 0, 1857.907011218729, 505.1108079590136;
 0, 0, 1]
R:
[0.58653194, 0.09898302, -0.80385488;
 -0.0056669, 0.99298114, 0.11813634;
 0.8099063, -0.06473536, 0.58297616]
Camera #2:
K:
[1956.01661889738, 0, 977.340049000778;
 0, 1858.884042017119, 452.6910870518543;
 0, 0, 1]
R:
[0.92483199, 0.025732817, -0.37950438;
 0.0063777552, 0.9965198, 0.08311265;
 0.38032237, -0.079285622, 0.9214493]
Camera #3:
K:
[2027.827899767372, 0, 930.3503442356033;
 0, 1893.313732155926, 500.6865883801996;
 0, 0, 1]
R:
[0.93531376, -0.036812913, 0.35189939;
 -0.0016524697, 0.99410725, 0.1083877;
 -0.35381576, -0.10195801, 0.92974138]
Camera #4:
K:
[2074.629130188972, 0, 981.7349428496174;
 0, 1914.593396587306, 501.3284095963675;
 0, 0, 1]
R:
[0.5458526, -0.10353445, 0.83145988;
 -0.0018850662, 0.99218208, 0.12478531;
 -0.83787918, -0.069681741, 0.54139]
warped_image_scale: 1996.72
roi[1884 x 1130 from (-2873, 2842)]
roi[1872 x 1127 from (-1734, 2825)]
roi[1827 x 1109 from (-166, 2837)]
roi[1803 x 1098 from (1065, 2874)]
[StitchingParamGenerator] Initialized.
[GetReprojParams] projected_image_roi_vect_refined: 
[GetReprojParams] roi [0: 1512x1072 from (0, 32)]
[GetReprojParams] roi [1: 1348x1072 from (372, 49)]
[GetReprojParams] roi [2: 1377x1072 from (152, 37)]
[GetReprojParams] roi [3: 1505x1072 from (298, 0)]
[SetParams] Setting params...
[CreateWeightMap] Creating weight map...
[CreateWeightMap] Creating weight map... Done.
[SetParams] Setting params... Done.
[SensorDataInterface] Getting new images... Done.
[WarpImages] Warping images 0 of 4...
[WarpImages] Remapping 0:4 ...
[WarpImages] Warping images 1 of 4...
[WarpImages] Remapping 1:4 ...
[WarpImages] Warping images 2 of 4...
[WarpImages] Remapping 2:4 ...
[WarpImages] Warping images 3 of 4...
[WarpImages] Remapping 3:4 ...
[WarpImages] Remapped 3:4 ...
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.5) /home/slam/Softwares/opencv-4.5.5/modules/core/src/umatrix.cpp:800: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'UMat'

Aborted (core dumped)

**Comment by duchengyao** [comment]
#10 

看起来是同一个问题，你能试一下这个分支再给我个log吗

你是什么系统

https://github.com/duchengyao/gpu-based-image-stitching/tree/test-assertion-failed
