### ISSUE TITLE
“D”畸变矩阵参数为啥是4个数，不是5个

### ISSUE THREAD

**Issue by peidongha** [duchengyao/gpu-based-image-stitching#13]
您好，我想问下
1、相机参数中，为什么“D”相机畸变参数正常是5个数，咱们里面是4个数；
2、如果我想利用6个相机进行全景拼接，只需要在您计算图像数量这里添加对应文件，同时添加6个相机参数文件就可以吧？下面是对应代码部分截图：

![20231227-132528](https://github.com/duchengyao/gpu-based-image-stitching/assets/37918885/277cd73b-1264-4e8e-8f39-d9fa4b8956de)

<img src="https://github.com/duchengyao/gpu-based-image-stitching/assets/37918885/1daaa832-cc8a-4d59-b5a3-d5a2f3436036" height="200px" >

**Comment by peidongha** [comment]
您好，我刚了解到“D”去畸变参数，常用的是前4个

**Comment by duchengyao** [comment]
1. https://github.com/duchengyao/gpu-based-image-stitching/issues/4 可以看一下这个issue
2. 是的

**Comment by peidongha** [comment]
新年快乐
我想问下这个工程用的opencv那个版本，我目前用opencv4.8.0，编译工程时无法用SIFI模块，如下图：

![Uvs65TPyfX](https://github.com/duchengyao/gpu-based-image-stitching/assets/37918885/7cd410e4-01cd-4bfa-bdfe-90d911b46577)

**Comment by duchengyao** [comment]
@peidongha 与版本无关，sift 有专利保护，opencv 编译的时候需要加上类似 enable_nonfree 开关，具体可以自己搜一下。
