### ISSUE TITLE
您好，有没有camchain_x.yam的摄像头标定的教程啊？ 

### ISSUE THREAD

**Issue by LoveChina-3000** [duchengyao/gpu-based-image-stitching#15]
您好，有没有camchain_x.yam的摄像头标定的教程啊？找了下没找到相关的教程，之前没有接触过这个东西。issues 4看过了，还是没理解

**Comment by LoveChina-3000** [comment]
大佬，还有一个问题请教下，如果不用标定这些参数，直接还是UMat的全景拼接可以吗？

**Comment by duchengyao** [comment]
https://github.com/duchengyao/gpu-based-image-stitching/issues/4

kalibr: https://www.bilibili.com/video/BV1gA411w7EM/

opencv: https://zhuanlan.zhihu.com/p/532797417

不标定也能用的

**Comment by LoveChina-3000** [comment]
感谢大佬，我试试标定下试试，谢谢

**Comment by duchengyao** [comment]
我先关掉这个issue了，有问题可以继续回复
