### ISSUE TITLE
你好，我的程序跑起来了，但是拼接结果图像好像没有保存，找不到

### ISSUE THREAD

**Issue by YAOJI01** [duchengyao/gpu-based-image-stitching#16]

**Comment by duchengyao** [comment]
https://github.com/duchengyao/gpu-based-image-stitching/blob/b3d7d5f8f25fe83b0abe17434555d3729921c2ff/src/app.cc#L93

这一行地址设置一下看看

**Comment by YAOJI01** [comment]
imwrite("F:/paperProject/myCode/result" + std::to_string(frame_idx) + ".png",
        image_concat_umat_); 还是没有，而且程序一直跑停不下来

**Comment by duchengyao** [comment]
你自己学一下opencv然后debug一下吧
