### ISSUE TITLE
最后一个摄像头的图像拼接出现错位

### ISSUE THREAD

**Issue by YAOJI01** [duchengyao/gpu-based-image-stitching#17]
你好，前三个摄像头的图像拼的比较好，最后一幅出现错位
![result0](https://github.com/duchengyao/gpu-based-image-stitching/assets/138271514/9d4f5c2c-adfb-45b0-9438-b253c592e9f4)

**Comment by duchengyao** [comment]
你自己研究一下吧 ^_^
