### ISSUE TITLE
您好，运行的环境是怎样的

### ISSUE THREAD

**Issue by huang1332** [duchengyao/gpu-based-image-stitching#3]
我试了windows 上编译opencv的GPU版，4.5.2和4.6和4.7都不行，按照这个链接的https://blog.csdn.net/weixin_43945848/article/details/125177533

**Comment by duchengyao** [comment]
@huang1332 应该是 3.x 以上的都行，错误信息提供一下。

**Comment by huang1332** [comment]
![image](https://user-images.githubusercontent.com/38836674/221181688-aa68ab0f-4cee-47b5-916c-3bfef355c282.png)

**Comment by duchengyao** [comment]
@huang1332 

版本应该没问题，好像是特征点匹配的时候出问题了。你用VS单步调试功能，看一下在代码的哪一行出错的。然后那一行变量的值都打印出来，看看有没有异常。
