### ISSUE TITLE
How to set up to achieve real-time stitching？

### ISSUE THREAD

**Issue by lio5474** [duchengyao/gpu-based-image-stitching#5]
I ran your program, but the fps is only around 3. At the same time, the program is constantly in the loop of stitching, and it does not stop until the last frame of the video, so that there is no final panoramic video output. Which of my settings need to be changed? Looking forward to your response.

**Comment by duchengyao** [comment]
Please paste full log output here if possible

**Comment by lio5474** [comment]
您好 运行之后终端输出是这样的，ocl.cpp有两个警告输出，FPS只能维持在3左右

Features in image #1: 5907
Features in image #2: 7816
Features in image #3: 8922
Features in image #4: 9958
Pairwise matchingInitial camera intrinsics #1:
K:
[2039.646716857912, 0, 1083.878127737308;
 0, 1400.203058539376, 387.0710143823282;
 0, 0, 1]
R:
[0.60557282, 0.068508461, -0.79283559;
 -0.0076580169, 0.99674314, 0.080278754;
 0.79575312, -0.04254308, 0.60412514]
Initial camera intrinsics #2:
K:
[1936.911037342978, 0, 1057.780573650494;
 0, 1366.504946426079, 365.2844838832723;
 0, 0, 1]
R:
[0.93487161, 0.014968796, -0.35467029;
 0.0054032817, 0.99839485, 0.056379527;
 0.35494491, -0.054624002, 0.93329012]
Initial camera intrinsics #3:
K:
[2003.413794397378, 0, 858.7282390744767;
 0, 1400.939172375516, 411.0322368884882;
 0, 0, 1]
R:
[0.94567609, -0.032977629, 0.32343364;
 0.0033208583, 0.99577016, 0.091820024;
 -0.32509357, -0.085757919, 0.94178545]
Initial camera intrinsics #4:
K:
[2134.620428732897, 0, 946.1090415929305;
 0, 1448.959289580109, 400.4034593365018;
 0, 0, 1]
R:
[0.56020087, -0.084141769, 0.82407236;
 -0.0063447189, 0.99436277, 0.10584237;
 -0.82833254, -0.064521492, 0.55650902]
warped_image_scale: 2021.53
roi[1843 x 1474 from (-2877, 2792)]
roi[1906 x 1502 from (-1775, 2761)]
roi[1881 x 1477 from (-189, 2784)]
roi[1796 x 1432 from (1093, 2844)]
[image_stitcher] 4.05e-07;0.00278277;1.25e-07;356.314
[ WARN:56@3.961] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[ WARN:57@3.961] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[ WARN:58@3.961] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[ WARN:57@3.967] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[ WARN:56@3.967] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[image_stitcher] 3.543e-06;0.00111851;1.07e-07;59.6635
[image_stitcher] [ WARN:58@3.968] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

4e-07;0.00161739;7.5e-08;59.2283
[image_stitcher] 5.3e-07;0.00209388;9.7e-08;59.4082
[app] 3.003e-06;0.0175054
57.1155 FPS; 2.96582 Real FPS.
[image_stitcher] 5.39e-07;0.00016615;9.4e-08;5670.77
[image_stitcher] 5.8e-07;6.291e-05;7.6e-08;5954.01
[image_stitcher] 7.29e-07;8.5424e-05;1.03e-07;4594.43
[image_stitcher] 5.47e-07;8.1955e-05;9.7e-08;5256.27
[app] 5.784e-06;0.000533976
1852.68 FPS; 3.20249 Real FPS.

**Comment by lio5474** [comment]
这是我的opencv版本信息：
General configuration for OpenCV 4.7.0 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            /home/c115/lx/opencv/opencv_contrib-4.7.0/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2023-06-09T02:07:30Z
    Host:                        Linux 5.4.0-148-generic x86_64
    CMake:                       3.25.3
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (14 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (30 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (5 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++ standard:                11
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -fsigned-char -ffast-math -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -ffast-math -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -ffast-math -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -ffast-math -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    Linker flags (Debug):        -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          m pthread cudart_static dl rt nppc nppial nppicc nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 alphamat aruco barcode bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dnn dnn_objdetect dnn_superres dpm features2d flann freetype fuzzy hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot quality rapid reg rgbd saliency sfm shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    face python_tests wechat_qrcode world
    Disabled by dependency:      -
    Unavailable:                 cvv gapi java julia matlab ovis python2 python3 viz
    Applications:                apps
    Documentation:               NO
    Non-free algorithms:         NO

  GUI:                           GTK3
    GTK+:                        YES (ver 3.22.30)
      GThread :                  YES (ver 2.56.4)
      GtkGlExt:                  NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
    JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver 80)
    PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
    TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
    JPEG 2000:                   OpenJPEG (ver 2.4.0)
    OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2_2)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      YES (2.2.5)
    FFMPEG:                      YES
      avcodec:                   YES (57.107.100)
      avformat:                  YES (57.83.100)
      avutil:                    YES (55.78.100)
      swscale:                   YES (4.8.100)
      avresample:                YES (3.7.0)
    GStreamer:                   YES (1.14.5)
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   /home/c115/lx/opencv/opencv-4.7.0/build/3rdparty/ippicv/ippicv_lnx/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                /home/c115/lx/opencv/opencv-4.7.0/build/3rdparty/ippicv/ippicv_lnx/iw
    VA:                          NO
    Lapack:                      NO
    Eigen:                       YES (ver 3.3.4)
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)

  NVIDIA CUDA:                   YES (ver 11.3, CUFFT CUBLAS FAST_MATH)
    NVIDIA GPU arch:             75
    NVIDIA PTX archs:

  cuDNN:                         YES (ver 8.9.1)

  OpenCL:                        YES (no extra features)
    Include path:                /home/c115/lx/opencv/opencv-4.7.0/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /usr/local
-----------------------------------------------------------------

**Comment by lio5474** [comment]
> @lio5474 Please paste full log output here if possible
您好 运行之后终端输出是这样的，ocl.cpp有两个警告输出，FPS只能维持在3左右

Features in image https://github.com/duchengyao/gpu-based-image-stitching/issues/1: 5907
Features in image https://github.com/duchengyao/gpu-based-image-stitching/issues/2: 7816
Features in image https://github.com/duchengyao/gpu-based-image-stitching/issues/3: 8922
Features in image https://github.com/duchengyao/gpu-based-image-stitching/issues/4: 9958
Pairwise matchingInitial camera intrinsics https://github.com/duchengyao/gpu-based-image-stitching/issues/1:
K:
[2039.646716857912, 0, 1083.878127737308;
0, 1400.203058539376, 387.0710143823282;
0, 0, 1]
R:
[0.60557282, 0.068508461, -0.79283559;
-0.0076580169, 0.99674314, 0.080278754;
0.79575312, -0.04254308, 0.60412514]
Initial camera intrinsics https://github.com/duchengyao/gpu-based-image-stitching/issues/2:
K:
[1936.911037342978, 0, 1057.780573650494;
0, 1366.504946426079, 365.2844838832723;
0, 0, 1]
R:
[0.93487161, 0.014968796, -0.35467029;
0.0054032817, 0.99839485, 0.056379527;
0.35494491, -0.054624002, 0.93329012]
Initial camera intrinsics https://github.com/duchengyao/gpu-based-image-stitching/issues/3:
K:
[2003.413794397378, 0, 858.7282390744767;
0, 1400.939172375516, 411.0322368884882;
0, 0, 1]
R:
[0.94567609, -0.032977629, 0.32343364;
0.0033208583, 0.99577016, 0.091820024;
-0.32509357, -0.085757919, 0.94178545]
Initial camera intrinsics https://github.com/duchengyao/gpu-based-image-stitching/issues/4:
K:
[2134.620428732897, 0, 946.1090415929305;
0, 1448.959289580109, 400.4034593365018;
0, 0, 1]
R:
[0.56020087, -0.084141769, 0.82407236;
-0.0063447189, 0.99436277, 0.10584237;
-0.82833254, -0.064521492, 0.55650902]
warped_image_scale: 2021.53
roi[1843 x 1474 from (-2877, 2792)]
roi[1906 x 1502 from (-1775, 2761)]
roi[1881 x 1477 from (-189, 2784)]
roi[1796 x 1432 from (1093, 2844)]
[image_stitcher] 4.05e-07;0.00278277;1.25e-07;356.314
[ WARN:56@3.961] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[ WARN:57@3.961] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[ WARN:58@3.961] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[ WARN:57@3.967] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[ WARN:56@3.967] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

[image_stitcher] 3.543e-06;0.00111851;1.07e-07;59.6635
[image_stitcher] [ WARN:58@3.968] global ocl.cpp:4504 compileWithCache Can't save OpenCL binary into cache: /home/c115/.cache/opencv/4.x/opencl_cache/NVIDIA_Corporation--NVIDIA_GeForce_RTX_2080_Ti--470_182_03/core--arithm_61e807be22793264eddbe34d6e91e620.bin
OpenCV(4.7.0) /home/c115/lx/opencv/opencv-4.7.0/modules/core/src/ocl.cpp:792: error: (-215:Assertion failed) !f.fail() in function 'write'

4e-07;0.00161739;7.5e-08;59.2283
[image_stitcher] 5.3e-07;0.00209388;9.7e-08;59.4082
[app] 3.003e-06;0.0175054
57.1155 FPS; 2.96582 Real FPS.
[image_stitcher] 5.39e-07;0.00016615;9.4e-08;5670.77
[image_stitcher] 5.8e-07;6.291e-05;7.6e-08;5954.01
[image_stitcher] 7.29e-07;8.5424e-05;1.03e-07;4594.43
[image_stitcher] 5.47e-07;8.1955e-05;9.7e-08;5256.27
[app] 5.784e-06;0.000533976
1852.68 FPS; 3.20249 Real FPS.

**Comment by lio5474** [comment]
> @lio5474 Please paste full log output here if possible

这是我的opencv版本信息：
General configuration for OpenCV 4.7.0 =====================================
Version control: unknown

Extra modules:
Location (extra): /home/c115/lx/opencv/opencv_contrib-4.7.0/modules
Version control (extra): unknown

Platform:
Timestamp: 2023-06-09T02:07:30Z
Host: Linux 5.4.0-148-generic x86_64
CMake: 3.25.3
CMake generator: Unix Makefiles
CMake build tool: /usr/bin/make
Configuration: Release

CPU/HW features:
Baseline: SSE SSE2 SSE3
requested: SSE3
Dispatched code generation: SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
requested: SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
SSE4_1 (14 files): + SSSE3 SSE4_1
SSE4_2 (1 files): + SSSE3 SSE4_1 POPCNT SSE4_2
FP16 (0 files): + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
AVX (4 files): + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
AVX2 (30 files): + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
AVX512_SKX (5 files): + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

C/C++:
Built as dynamic libs?: YES
C++ standard: 11
C++ Compiler: /usr/bin/c++ (ver 7.5.0)
C++ flags (Release): -fsigned-char -ffast-math -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -DNDEBUG
C++ flags (Debug): -fsigned-char -ffast-math -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g -O0 -DDEBUG -D_DEBUG
C Compiler: /usr/bin/cc
C flags (Release): -fsigned-char -ffast-math -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG -DNDEBUG
C flags (Debug): -fsigned-char -ffast-math -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections -msse -msse2 -msse3 -fvisibility=hidden -g -O0 -DDEBUG -D_DEBUG
Linker flags (Release): -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined
Linker flags (Debug): -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined
ccache: NO
Precompiled headers: NO
Extra dependencies: m pthread cudart_static dl rt nppc nppial nppicc nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu
3rdparty dependencies:

OpenCV modules:
To be built: alphamat aruco barcode bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dnn dnn_objdetect dnn_superres dpm features2d flann freetype fuzzy hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot quality rapid reg rgbd saliency sfm shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
Disabled: face python_tests wechat_qrcode world
Disabled by dependency: -
Unavailable: cvv gapi java julia matlab ovis python2 python3 viz
Applications: apps
Documentation: NO
Non-free algorithms: NO

GUI: GTK3
GTK+: YES (ver 3.22.30)
GThread : YES (ver 2.56.4)
GtkGlExt: NO
VTK support: NO

Media I/O:
ZLib: /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (ver 80)
PNG: /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
JPEG 2000: OpenJPEG (ver 2.4.0)
OpenEXR: /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2_2)
HDR: YES
SUNRASTER: YES
PXM: YES
PFM: YES

Video I/O:
DC1394: YES (2.2.5)
FFMPEG: YES
avcodec: YES (57.107.100)
avformat: YES (57.83.100)
avutil: YES (55.78.100)
swscale: YES (4.8.100)
avresample: YES (3.7.0)
GStreamer: YES (1.14.5)
v4l/v4l2: YES (linux/videodev2.h)

Parallel framework: pthreads

Trace: YES (with Intel ITT)

Other third-party libraries:
Intel IPP: 2020.0.0 Gold [2020.0.0]
at: /home/c115/lx/opencv/opencv-4.7.0/build/3rdparty/ippicv/ippicv_lnx/icv
Intel IPP IW: sources (2020.0.0)
at: /home/c115/lx/opencv/opencv-4.7.0/build/3rdparty/ippicv/ippicv_lnx/iw
VA: NO
Lapack: NO
Eigen: YES (ver 3.3.4)
Custom HAL: NO
Protobuf: build (3.19.1)

NVIDIA CUDA: YES (ver 11.3, CUFFT CUBLAS FAST_MATH)
NVIDIA GPU arch: 75
NVIDIA PTX archs:

cuDNN: YES (ver 8.9.1)

OpenCL: YES (no extra features)
Include path: /home/c115/lx/opencv/opencv-4.7.0/3rdparty/include/opencl/1.2
Link libraries: Dynamic load

Python (for build): /usr/bin/python2.7

Java:
ant: NO
JNI: NO
Java wrappers: NO
Java tests: NO

Install to: /usr/local

**Comment by duchengyao** [comment]
@lio5474 

`57.1155 FPS; 2.96582 Real FPS.` 拼接的帧率是57，总帧率是2.9，时间都花在imwrite了，所以是正常的。你看一下代码 t2 跟 tn 的位置就知道了。

https://github.com/duchengyao/gpu-based-image-stitching/blob/a9dbf3b0b36b2de9c1bbadffd14d018051efe1f2/src/app.cc#L103C1-L104

`(-215:Assertion failed) !f.fail() in function 'write'` 这些 warnning，我觉得可以不用管它。

至于没保存图片的原因，你提供一下目录结构吧，可能是没找到`../results/`这个文件夹，代码：

https://github.com/duchengyao/gpu-based-image-stitching/blob/a9dbf3b0b36b2de9c1bbadffd14d018051efe1f2/src/app.cc#L94

**Comment by duchengyao** [comment]
imwrite 确实耗费时间很大，使用的时候会在后面接rtsp推流。如果你只要测试，可以把每一帧图片 emplace_back 到 vector 里（记得提前分配空间）。所有拼接执行完毕以后，再把vector的图片都存下来。

**Comment by lio5474** [comment]
> imwrite 涉及磁盘操作，确实耗费时间很多，我使用的时候会在后面接rtsp推流。
> 
> 如果你只要测试，可以把每一帧图片 emplace_back 到 vector 里（记得提前分配空间）。 所有拼接执行完毕以后，再把vector的图片都存下来。

谢谢~ 确实是imwrite耗时过多，我试了将imwrite注释，处理速度达到了400+FPS。
