### ISSUE TITLE
运行测试视频不会停止

### ISSUE THREAD

**Issue by renyiyu** [duchengyao/gpu-based-image-stitching#6]
您好，我编译好了代码，运行了测试视频，但是代码好像不会停止运行，一直会在result的目录里面生成图片，也不会合成最后的视频。我看了一下几段视频实际都只有5秒钟，不知道为什么会一直运行过去。terminal里显示拼接速度大概在3000fps左右，imwrite在5fps左右。

**Comment by renyiyu** [comment]
Features in image #1: 5907
Features in image #2: 7816
Features in image #3: 8922
Features in image #4: 9958
Pairwise matchingInitial camera intrinsics #1:
K:
[1958.933071501763, 0, 1032.073326520884;
 0, 1803.802234036233, 492.9395066688497;
 0, 0, 1]
R:
[0.58928597, 0.096246459, -0.80217111;
 -0.0060473438, 0.99337661, 0.11474531;
 0.8079018, -0.062766813, 0.58596504]
Initial camera intrinsics #2:
K:
[1940.775049616609, 0, 979.821219671406;
 0, 1800.030664318595, 444.3127397091786;
 0, 0, 1]
R:
[0.92561078, 0.024925742, -0.37765497;
 0.0061234771, 0.99671221, 0.080792651;
 0.37842712, -0.077095114, 0.9224149]
Initial camera intrinsics #3:
K:
[2029.041748335749, 0, 907.6919741788095;
 0, 1842.200940636714, 491.1150962266445;
 0, 0, 1]
R:
[0.93743664, -0.036371075, 0.34625065;
 -0.00062188756, 0.99435186, 0.10613303;
 -0.3481552, -0.099708326, 0.93211925]
Initial camera intrinsics #4:
K:
[2091.118206726335, 0, 985.7049172031401;
 0, 1870.090944356822, 489.9460877840248;
 0, 0, 1]
R:
[0.54313946, -0.10075304, 0.83357549;
 -0.0028010455, 0.99255162, 0.12179335;
 -0.83963782, -0.068485662, 0.53881168]
Camera #1:
K:
[1958.933071501763, 0, 1032.073326520884;
 0, 1803.802234036233, 492.9395066688497;
 0, 0, 1]
R:
[0.58928597, 0.096246459, -0.80217111;
 -0.0060473438, 0.99337661, 0.11474531;
 0.8079018, -0.062766813, 0.58596504]
Camera #2:
K:
[1940.775049616609, 0, 979.821219671406;
 0, 1800.030664318595, 444.3127397091786;
 0, 0, 1]
R:
[0.92561078, 0.024925742, -0.37765497;
 0.0061234771, 0.99671221, 0.080792651;
 0.37842712, -0.077095114, 0.9224149]
Camera #3:
K:
[2029.041748335749, 0, 907.6919741788095;
 0, 1842.200940636714, 491.1150962266445;
 0, 0, 1]
R:
[0.93743664, -0.036371075, 0.34625065;
 -0.00062188756, 0.99435186, 0.10613303;
 -0.3481552, -0.099708326, 0.93211925]
Camera #4:
K:
[2091.118206726335, 0, 985.7049172031401;
 0, 1870.090944356822, 489.9460877840248;
 0, 0, 1]
R:
[0.54313946, -0.10075304, 0.83357549;
 -0.0028010455, 0.99255162, 0.12179335;
 -0.83963782, -0.068485662, 0.53881168]
warped_image_scale: 1993.99
roi[1887 x 1159 from (-2875, 2829)]
roi[1882 x 1160 from (-1736, 2810)]
roi[1823 x 1137 from (-159, 2824)]
roi[1788 x 1121 from (1074, 2864)]
[image_stitcher] 1.25e-07;0.00049519;3e-08;384.309
[image_stitcher] 2.24e-07;0.00272741;3.9e-08;366.299
[image_stitcher] 2.56e-07;0.000178858;4.1e-08;356.875
[image_stitcher] 2.24e-07;0.00199455;3.3e-08;293.226
[app] 1.587e-06;0.00371146
269.321 FPS; 9.38649 Real FPS.
[image_stitcher] 1.609e-06;6.8794e-05;3.1e-08;12280.6
[image_stitcher] [image_stitcher] 2.24e-07;2.01e-07;3.7732e-05;4.5187e-05;2.9e-08;3e-08;13837.8
13567.8
[image_stitcher] 1.91e-07;6.4971e-05;2.9e-08;11089.9
[app] 2.717e-06;0.000348466
2847.52 FPS; 9.73403 Real FPS.
[image_stitcher] 2.25e-07;5.5665e-05;3e-08;17040.4
[image_stitcher] 1.92e-07;4.3016e-05;3.1e-08;10557.1
[image_stitcher] 1.655e-06;3.9103e-05;2.9e-08;14773.2
[image_stitcher] 5.02e-07;2.9269e-05;3e-08;13835.3
[app] 1.864e-06;0.000298061
3334.17 FPS; 9.74956 Real FPS.
[image_stitcher] 1.615e-06;7.2552e-05;2.9e-08;12016.6
[image_stitcher] [image_stitcher] 2.02e-07;3.6608e-05;3e-08;2.26e-07;14259.2
3.1181e-05;3e-08;13890.4
[image_stitcher] 2.39e-07;2.4033e-05;3e-08;19374.6
[app] 1.587e-06;0.000305492
3256.49 FPS; 9.65665 Real FPS.
[image_stitcher] 1.91e-07;5.7706e-05;2.9e-08;13696
[image_stitcher] 1.635e-06;3.1705e-05;3e-08;[image_stitcher] 15274.4
1.655e-06;3.3611e-05;2.9e-08;[image_stitcher] 13449.7
2.24e-07;3.306e-05;3e-08;13363.1
[app] 1.981e-06;0.000307966
3226.36 FPS; 9.72267 Real FPS.
[image_stitcher] 1.88e-07;5.8137e-05;3.1e-08;14227.4
[image_stitcher] 1.634e-06;4.2003e-05;3e-08;[image_stitcher] 11271.2
1.641e-06[image_stitcher] ;4.8858e-05;3e-08;10099.5
1.562e-06;6.1251e-05;2.9e-08;10242.6
[app] 1.856e-06;0.000402915
2470.53 FPS; 9.73407 Real FPS.
[image_stitcher] 2.54e-07;6.8716e-05;2.9e-08;12391.3
[image_stitcher] [image_stitcher] 1.629e-06;[image_stitcher] 4.1892e-05;3.1e-08;1.667e-06;13054.1
4.7706e-05;2.9e-08;12538.6
1.537e-06;5.5895e-05;3e-08;11631.6
[app] 1.943e-06;0.000311214
3193.29 FPS; 9.7253 Real FPS.
[image_stitcher] 1.705e-06;5.5737e-05;2.9e-08;16494
[image_stitcher] 1.578e-06;3.5167e-05;3e-08;14732.5
[image_stitcher] 2.43e-07;5.0604e-05;3e-08;12716.2
[image_stitcher] 1.644e-06;2.5976e-05;2.9e-08;19799.6
[app] 2.027e-06;0.000304708
3260.14 FPS; 9.74028 Real FPS.
[image_stitcher] 1.21e-07;5.6104e-05;3e-08;7161.32
[image_stitcher] 1.589e-06;7.6554e-05;3e-08;12238.3
[image_stitcher] 1.606e-06;3.4671e-05;3e-08;14750.1
[image_stitcher] 2.21e-07;4.2893e-05;2.9e-08;13673
[app] 1.853e-06;0.000319837
3108.58 FPS; 9.70891 Real FPS.
[image_stitcher] 2.27e-07;6.0354e-05;3.2e-08;12567.6
[image_stitcher] 1.582e-06;3.6066e-05;3e-08;[image_stitcher] 13945.6
[image_stitcher] 1.65e-06;3.9315e-05;1.623e-063e-08;;3.7712e-05;122423e-08;
11790.2
[app] 1.891e-06;0.00031634
3142.37 FPS; 9.54204 Real FPS.
[image_stitcher] 2.08e-07;6.2763e-05;3e-08;14856.9
[image_stitcher] [image_stitcher] 1.336e-06;3.1861e-05;3e-08;5.29e-07;10355.5
4.7563e-05;3e-08;10259.1
[image_stitcher] 2.31e-07;3.0305e-05;3.6e-08;11301.2
[app] 0.00066387;0.000398676
941.136 FPS; 8.68737 Real FPS.
[image_stitcher] 2.44e-07;6.2932e-05;3.1e-08;15100.3
[image_stitcher] 1.98e-07;3.0525e-05;3e-08;15318.6
[image_stitcher] 1.32e-07;2.7771e-05;3e-08;18557.4
[image_stitcher] 1.99e-07;3.8465e-05;2.9e-08;11652
[app] 2.175e-06;0.000265369
3737.7 FPS; 8.79068 Real FPS.
[image_stitcher] 1.661e-06;5.8115e-05;3e-08;15812.8
[image_stitcher] 1.9e-07;6.0061e-05;3e-08;10284
[image_stitcher] 2.27e-07;2.8463e-05;2.9e-08;[image_stitcher] 17690.3
2.15e-07;3.1268e-05;3e-08;16538.5
[app] 1.835e-06;0.000309241
3214.65 FPS; 8.74663 Real FPS.
[image_stitcher] 2.07e-07;4.6097e-05;3e-08;20201.6
[image_stitcher] 2.52e-07;5.6101e-05;3.1e-08;9299.64
[image_stitcher] 2.08e-07;3.788e-05;3.1e-08;13756.3
[image_stitcher] 2.5e-07;4.7927e-05;3e-08;12102.7
[app] 2.28e-06;0.000348062
2854.35 FPS; 8.72935 Real FPS.
[image_stitcher] 3.31e-07;5.9261e-05;3e-08;6555.01
[image_stitcher] 2.67e-07;3.0148e-05;3e-08;5983.65
[image_stitcher] 2.1e-07;2.8549e-05;3.1e-08;4469.17
[image_stitcher] 1.574e-06;4.8184e-05;2.9e-08;3334.9
[app] 2.014e-06;0.000523166
1904.11 FPS; 8.73658 Real FPS.
[image_stitcher] 2.15e-07;5.2452e-05;3e-08;15496.4
[image_stitcher] 1.582e-06;4.562e-05;3e-08;[image_stitcher] 9233.95
[image_stitcher] 1.55e-06;8.8148e-05;2.9e-08;8250.42
1.608e-06;5.185e-05;3.1e-08;8421.48
[app] 1.347e-06;0.000416411
2393.73 FPS; 8.74805 Real FPS.
[image_stitcher] 2.71e-07;5.6586e-05;3.1e-08;14806.9
[image_stitcher] 1.035e-06;2.7625e-05;2.6e-08;16129.6
[image_stitcher] 2.05e-07;2.3158e-05;[image_stitcher] 2.9e-08;16815.2
1.615e-06;5.0075e-05;2.9e-08;10977.1
[app] 1.668e-06;0.000276899
3589.8 FPS; 8.75369 Real FPS.
[image_stitcher] 1.22e-07;5.5219e-05;3e-08;7099.2
[image_stitcher] 1.667e-06;8.1892e-05;2.9e-08;11554.9
[image_stitcher] [image_stitcher] 1.93e-07;3.0031e-05;3e-08;17406.4
1.614e-06;3.7619e-05;3.1e-08;15351.6
[app] 1.798e-06;0.000308809
3219.5 FPS; 8.71243 Real FPS.
[image_stitcher] 2.9e-07;5.9683e-05;3e-08;15789.3
[image_stitcher] 2.53e-07;3.0941e-05;3e-08;13519.4
[image_stitcher] 2.42e-07;5.129e-05;3e-08;11511.5
[image_stitcher] 1.646e-06;5.2218e-05;2.9e-08;9799.69
[app] 1.568e-06;0.000302475
3289.01 FPS; 8.72191 Real FPS.
[image_stitcher] 2.24e-07;6.8113e-05;3.2e-08;9634.93
[image_stitcher] 2.32e-07;3.4834e-05;3e-08;10199.5
[image_stitcher] [image_stitcher] 2.109e-06;4.1375e-05;3.2e-08;8584.28
2.16e-07;7.292e-05;2.9e-08;8590.47
[app] 0.000643264;0.000317183
1041.18 FPS; 8.57435 Real FPS.
[image_stitcher] 3.02e-07;6.148e-05;2.9e-08;13811.8
[image_stitcher] 2.19e-07;4.906e-05;3e-08;10052.9
[image_stitcher] 1.67e-06;2.777e-05;3e-08;16906.2
[image_stitcher] 2.63e-07;2.6758e-05;2.9e-08;15033.1
[app] 2.01e-06;0.000269182
3687.42 FPS; 8.64212 Real FPS.
[image_stitcher] 9.8e-08;6.7215e-05;4e-08;7145.2
[image_stitcher] 2e-07;7.1074e-05;3.1e-08;13554.9
[image_stitcher] 1.537e-06;6.4332e-05;2.9e-08;[image_stitcher] 10276.8
1.2666e-05;4.9271e-05;3.1e-08;9299.9
[app] 1.618e-06;0.000309642
3212.75 FPS; 8.66358 Real FPS.
[image_stitcher] 8.4e-08;4.9358e-05;2.9e-08;7398.69
[image_stitcher] 2.07e-07;6.734e-05;3.2e-08;14257.8
[image_stitcher] 2.36e-07;[image_stitcher] 2.6089e-05;3e-08;15105.1
2.24e-07;2.4614e-05;3e-08;14487.5
[app] 1.953e-06;0.000315938
3145.73 FPS; 8.65326 Real FPS.
[image_stitcher] 1.599e-06;7.4581e-05;3e-08;12483.8
[image_stitcher] 2.03e-07;4.1148e-05;3e-08;9565.17
[image_stitcher] 2.6e-07;3.7596e-05;2.9e-08;8789.59
[image_stitcher] 2.46e-07;6.5877e-05;3e-08;10867.2
[app] 1.865e-06;0.000344659
2885.8 FPS; 8.64097 Real FPS.
[image_stitcher] 1.62e-06;6.9161e-05;3e-08;13471.8
[image_stitcher] 2.38e-07;3.5458e-05;2.9e-08;12303.6
[image_stitcher] 2.48e-07;[image_stitcher] 5.9149e-05;3e-08;11563
2.13e-07;2.7082e-05;3.1e-08;12584.3
[app] 1.927e-06;0.000412294
2414.17 FPS; 8.64189 Real FPS.

> 发一下完整的 log 看看

**Comment by renyiyu** [comment]
> 发一下完整的 log 看看

terminal 里面打印的信息在上面，然后一直结束不了，存了1w多张拼接好的大图了，磁盘快不够了

**Comment by piaolinzhe** [comment]
这个情况我也遇到了，确实是循环不停，可以加个循环次数在App::run_stitching() 里。另外，生成图片后，没有看到能合成视频的代码内容。

**Comment by duchengyao** [comment]
@renyiyu 之前没考虑到使用数据集的方式，我添加了一个 `dataset` 分支。拼接完以后会停止，但程序不会退出。[查看区别](https://github.com/duchengyao/gpu-based-image-stitching/commit/210fe9a17eb15a92f5d5eb9dc16d53605abbf44b)

@piaolinzhe 保存图片很低效，所以代码里面不考虑增加保存图片生成视频的内容，如果真的想生成视频可以使用 `ffmpeg`。可以搜索 `ffmpeg 图片合成视频`

**Comment by piaolinzhe** [comment]
@duchengyao 保存图片或视频都是为了测试，最终目的是输出视频，关于推出rtsp或rtmp流，能给一些实现思路么？

**Comment by duchengyao** [comment]
@piaolinzhe 我不懂推流，但是我觉得可以用 ffmpeg 的 C++ 接口，或者仿照 ffmpeg 的推流代码。
